spring:
  profiles: dev
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gift_cert
    username: postgres
    password: A@dmin123321
    initialSize: 10