spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:app-test
    driverClassName: org.h2.Driver
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql