spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/gift_cert
    username: postgres
    password: A@dmin123321
    driverClassName: org.postgresql.Driver
    hikari:
      pool-name: app-pool
      maximum-pool-size: 10